CREATE   PROCEDURE imp.usp_TherapeuticClassImport
AS
BEGIN
SELECT DISTINCT
TRIM(LEFT(CLASSETERAPEUTICA, CHARINDEX('-', CLASSETERAPEUTICA)-2)),
TRIM(RIGHT(CLASSETERAPEUTICA, LEN(CLASSETERAPEUTICA) - CHARINDEX('-', CLASSETERAPEUTICA)))
FROM [db_a9b211_intelipharma].[Imp].[Conformidade] c (nolock)
WHERE NULLIF(TRIM(CLASSETERAPEUTICA), '') IS NOT NULL
ORDER BY 1 DESC;
END;