CREATE TABLE [Imp].[Conformidade] (
    [SUBSTANCIA]                          VARCHAR (MAX) NULL,
    [CNPJ]                                VARCHAR (MAX) NULL,
    [LABORATORIO]                         VARCHAR (MAX) NULL,
    [CODIGO]                              VARCHAR (MAX) NULL,
    [GGREM]                               VARCHAR (MAX) NULL,
    [REGISTRO]                            VARCHAR (MAX) NULL,
    [EAN1]                                VARCHAR (MAX) NULL,
    [EAN2]                                VARCHAR (MAX) NULL,
    [PRODUTO]                             VARCHAR (MAX) NULL,
    [APRESENTACAO]                        VARCHAR (MAX) NULL,
    [CLASSETERAPEUTICA]                   VARCHAR (MAX) NULL,
    [TIPODEPRODUTO]                       VARCHAR (MAX) NULL,
    [REGIMEDEPRECO]                       VARCHAR (MAX) NULL,
    [PFSemImpostos]                       VARCHAR (MAX) NULL,
    [PF0%]                                VARCHAR (MAX) NULL,
    [PF12%]                               VARCHAR (MAX) NULL,
    [PF17%]                               VARCHAR (MAX) NULL,
    [PF17% ALC]                           VARCHAR (MAX) NULL,
    [PF17,5%]                             VARCHAR (MAX) NULL,
    [PF17,5% ALC]                         VARCHAR (MAX) NULL,
    [PF18%]                               VARCHAR (MAX) NULL,
    [PF18% ALC]                           VARCHAR (MAX) NULL,
    [PF19%]                               VARCHAR (MAX) NULL,
    [PF20%]                               VARCHAR (MAX) NULL,
    [PF21%]                               VARCHAR (MAX) NULL,
    [PF22%]                               VARCHAR (MAX) NULL,
    [PMC0%]                               VARCHAR (MAX) NULL,
    [PMC12%]                              VARCHAR (MAX) NULL,
    [PMC17%]                              VARCHAR (MAX) NULL,
    [PMC17% ALC]                          VARCHAR (MAX) NULL,
    [PMC17,5%]                            VARCHAR (MAX) NULL,
    [PMC17,5% ALC]                        VARCHAR (MAX) NULL,
    [PMC18%]                              VARCHAR (MAX) NULL,
    [PMC18% ALC]                          VARCHAR (MAX) NULL,
    [PMC19%]                              VARCHAR (MAX) NULL,
    [PMC20%]                              VARCHAR (MAX) NULL,
    [PMC21%]                              VARCHAR (MAX) NULL,
    [PMC22%]                              VARCHAR (MAX) NULL,
    [RESTRICAOHOSPITALAR]                 VARCHAR (MAX) NULL,
    [CAP]                                 VARCHAR (MAX) NULL,
    [CONFAZ87]                            VARCHAR (MAX) NULL,
    [ICMS0%]                              VARCHAR (MAX) NULL,
    [ANALISERECURSAL]                     VARCHAR (MAX) NULL,
    [LISTADECONCESSAODECREDITOTRIBUTARIO] VARCHAR (MAX) NULL,
    [COMERCIALIZACAO2022]                 VARCHAR (MAX) NULL,
    [TARJA]                               VARCHAR (MAX) NULL,
    [Data]                                VARCHAR (MAX) NULL
);



